export const AUTH_REQUEST = "AUTH_REQUEST";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const NOT_LOGGEDIN = "NOT_LOGGEDIN";
